In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Titanic.csv")
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [3]:
df.drop(['PassengerId','Name', 'Ticket'], axis = 1, inplace= True)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [4]:
dtypes = df.dtypes
n_uniq = df.nunique()
pd.DataFrame({"Dtype":dtypes, "Num_Uniqe":n_uniq}).T

          Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtype        int64  int64  str  float64  int64  int64  float64   str      str
Num_Uniqe        2      3    2       88      7      7      248   147        3

In [5]:
cols = ['Pclass','Survived','Sex','SibSp','Parch','Embarked']
df[cols] = df[cols].astype('category')

In [6]:
null = df.isnull().sum()
ratio = (null/ df.shape[0])*100
pd.DataFrame({"Null":null, "ratio":ratio}).T

       Survived  Pclass  Sex        Age  ...  Parch  Fare       Cabin  Embarked
Null        0.0     0.0  0.0  177.00000  ...    0.0   0.0  687.000000  2.000000
ratio       0.0     0.0  0.0   19.86532  ...    0.0   0.0   77.104377  0.224467

[2 rows x 9 columns]

In [7]:
median_1 = df['Age'].median()
df['Age'] = df['Age'].fillna(median_1)

In [46]:
df.dropna(subset=['Embarked'], inplace= True)
df.drop('Cabin',axis=1,inplace= True)

In [47]:
null = df.isnull().sum()
ratio = (null/ df.shape[0])*100
pd.DataFrame({"Null":null, "ratio % ":ratio}).T

          Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
Null           0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0
ratio %        0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0

In [10]:
num_cols = ["Age","Fare"]

In [11]:
# plt.figure(figsize=(8,1))
# for i , col in enumerate(num_cols):
#     plt.subplot(1,2, i+1)
#     sns.boxplot(df[col], orient="h")
#     plt.title(f"{col}  boxplot")
# plt.show()

In [12]:
# plt.figure(figsize=(8,1))
# for i , col in enumerate(num_cols):
#     plt.subplot(1,2,i+1)
#     sns.boxplot(df[col],orient = "h")

In [48]:
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(.75)
    # print(Q1,Q3)
    IQR = Q3 - Q1
    lower_fence = Q1 - 1.5* IQR
    upper_fence = Q3 + 1.5* IQR
    print(lower_fence)
    lower_outliers = df[ df[col] < lower_fence][col].values 
    upper_outliers = df[ df[col] > upper_fence][col].values 
    print(lower_outliers)
    
    df[col] = df[col].replace(lower_outliers, lower_fence)
    df[col] = df[col].replace(upper_outliers, upper_fence)

-1.5
[]
-29.374999999999996
[]

In [14]:
# plt.figure(figsize=(8,1))
# for i , col in enumerate(num_cols):
#     plt.subplot(1,2,i+1)
#     sns.boxplot(df[col],orient = "h")

In [15]:
# plt.figure(figsize=(8,1))
# for i , col in enumerate(num_cols):
#     plt.subplot(1,2, i+1)
#     sns.boxplot(df[col], orient="h")
#     plt.title(f"{col}  boxplot")
# plt.show()

In [16]:
df.duplicated().sum()

np.int64(116)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
# plt.figure(figsize=(9,2))
# for i , col in enumerate(num_cols):
#     plt.subplot(1,2,i+1)
#     plt.hist(df[col],edgecolor="black")
#     plt.title(f"{col} hist dist")

In [19]:
# plt.figure(figsize=(9,2))
# for i , col in enumerate(num_cols):
#     plt.subplot(1,2,i+1)
#     sns.kdeplot(data=df[col],fill=True)
#     plt.title(f"{col} hist dist")

In [20]:
cat_col = df.select_dtypes("category")
cat_col

    Survived Pclass     Sex SibSp Parch Embarked
0          0      3    male     1     0        S
1          1      1  female     1     0        C
2          1      3  female     0     0        S
3          1      1  female     1     0        S
4          0      3    male     0     0        S
..       ...    ...     ...   ...   ...      ...
885        0      3  female     0     5        Q
887        1      1  female     0     0        S
888        0      3  female     1     2        S
889        1      1    male     0     0        C
890        0      3    male     0     0        Q

[773 rows x 6 columns]

In [21]:
# plt.figure(figsize=(14,4))
# for i , col in enumerate(cat_col):
#     plt.subplot(2,3,i+1)
#     sns.countplot(x= col , data= df)
#     plt.title(f"{col} count plot")
# plt.subplots_adjust(hspace=0.8,wspace=0.3)
# plt.show()

In [22]:
# unique = df['Survived'].value_counts()
# print(unique)
# count = unique.values
# print(count)
# categories = unique.index
# print(categories)

In [23]:
# plt.figure(figsize=(14,4))
# for i , col in enumerate(cat_col):
#     plt.subplot(2,3,i+1)
#     unique = df[col].value_counts()
#     count = unique.values
#     categories = unique.index
#     plt.pie(count,labels=categories,startangle=140,autopct='%1.1d%%')

In [24]:
# import plotly.express as px

In [25]:
# fig = px.pie(df,names="Survived",labels=unique)
# fig.show()

In [26]:
# fig = px.pie(df,names="Survived",
#             color_discrete_sequence=px.colors.qualitative.Pastel,)
# fig.show()

In [27]:

# fig = px.pie(df,names="Survived",
#             color_discrete_sequence=px.colors.qualitative.Pastel,
#             hole= 0.6)
# fig.show()

# (1)data distribution graph

### 1- numerical distribution (Histgram) -> plt

In [28]:
num_cols

['Age', 'Fare']

In [29]:
# plt.figure(figsize=(8,2))
# for i , col in enumerate(num_cols):
# 	plt.subplot(1,2,i+1)
# 	plt.hist(df[col], edgecolor='black')
# 	plt.title(f"{col} histgram")

# plt.show()

### 2- numerical distribution (KDE plot) -> sns

In [30]:
# plt.figure(figsize=(8,2))
# for i , col in enumerate(num_cols):
# 	plt.subplot(1, 2, i+1)
# 	sns.kdeplot(df[col])
# 	plt.title(f"{col} KDE PLOT")

# plt.show()

### 1- categorical data distribution (countplot) -> sns

In [31]:
# cat_col

In [32]:
# plt.figure(figsize=(14,4))
# for i , col in enumerate(cat_col):
# 	plt.subplot(2, 3, i+1)
# 	sns.countplot(x= col , data= df)
# 	plt.title(f"{col} distribution graph")
# plt.subplots_adjust(hspace=0.8, wspace=0.3)
# plt.show()

### 2- categorical data distribution (pieplot) -> plt

In [33]:
# plt.figure(figsize=(14,4))
# for i , col in enumerate(cat_col):
# 	plt.subplot(2, 3, i+1)
# 	unique = df[col].value_counts()
# 	count = unique.values
# 	categories = unique.index
# 	plt.pie(count,labels=categories,startangle= 140,autopct='%1.1f%%')
# 	plt.title(f"{col} pie graph")
 
# plt.subplots_adjust(hspace=0.6, wspace=0.1)
# plt.show()

# (2) outliers - graph

### 1- box plot -> sns

In [34]:
# plt.figure(figsize=(10,1))
# for i , col in enumerate(num_cols):
#     plt.subplot(1,2,i+1)
#     sns.boxplot(df[col],orient='h',color="red")
#     plt.title(f"{col} box plot")
    
# plt.show()

# (3) relations - graph

### (1) relation --> numerical : numerical

#### 1- scatter  -> plt

In [35]:
# plt.figure(figsize=(4,4))
# plt.scatter(df['Age'],df['Fare'])
# plt.xlabel("age")
# plt.ylabel("fare")
# plt.show

#### 2- pair plot  -> sns

In [36]:
# plt.figure(figsize=(4,4))
# sns.pairplot(df)
# plt.xlabel("age")
# plt.ylabel("fare")
# plt.show

#### 3- line plot  -> plt

In [37]:
# sorted_df = df.sort_values(by = "Age")
# plt.figure(figsize=(4,4))
# plt.plot(sorted_df['Age'],sorted_df['Fare'])
# plt.show()

#### 4- heatmap  -> sns

In [38]:
# corr = df.corr(numeric_only= True)
# plt.figure(figsize=(4,4))
# sns.heatmap(corr,annot= True)
# plt.show()

### (2) relation --> numerical : categorical

### 1- bar plot -> sns

In [39]:
# plt.figure(figsize=(4,4))
# sns.barplot(x= "Survived", y="Fare" , data= df)
# plt.show()

### (3) relation --> categorical : categorical

### 1-heatmap -> sns

In [40]:
# plt.figure(figsize=(4,4))
# agg = df.pivot_table(index="Survived", columns="Sex", values="Age", aggfunc=len)
# sns.heatmap(agg)
# plt.show()

In [41]:
# cross = pd.crosstab(df["Survived"], df["Sex"])
# cross
# sns.heatmap(
#     cross,
#     annot=True,
#     fmt="d"
# )

In [42]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from category_encoders import OneHotEncoder

In [50]:
x = df.drop("Survived", axis=1)
y = df[['Survived']]

In [53]:
X_train,X_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state = 42)

In [56]:
df.head()

  Survived Pclass     Sex   Age SibSp Parch     Fare Embarked
0        0      3    male  22.0     1     0   7.2500        S
1        1      1  female  38.0     1     0  65.6563        C
2        1      3  female  26.0     0     0   7.9250        S
3        1      1  female  35.0     1     0  53.1000        S
4        0      3    male  35.0     0     0   8.0500        S

In [66]:
num_cols =df.select_dtypes("number").columns
str_col =df.select_dtypes("category").columns
print(str_col)
print(num_cols)

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'], dtype='str')
Index(['Age', 'Fare'], dtype='str')

In [ ]:

encoder = OneHotEncoder()
X_train_encoded = encoder.fit_transform(X_train[str_col])
X_test_encoded = encoder.transform(X_test[str_col])

In [ ]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train[num_cols])
X_test_scaled = scaler.transform(X_test[num_cols])